language: r
cache: packages
warnings_are_errors: false
sudo: false

addons:
  apt:
    packages:
      - libgeos-dev

r_check_args: "--no-build-vignettes --no-manual"
r_build_args: "--no-build-vignettes --no-manual"
repos:
  CRAN: https://cran.rstudio.com
